# Generated by Django 4.1.7 on 2023-08-20 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LiquidityPoolImporterBlockReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain", models.IntegerField()),
                ("chain_name", models.CharField(max_length=255)),
                ("dex", models.IntegerField()),
                ("dex_name", models.CharField(max_length=255)),
                ("liquidity_pool", models.IntegerField()),
                ("liquidity_pool_name", models.CharField(max_length=255)),
                ("block_number", models.IntegerField()),
                ("block_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lp_pool_block_reference",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_hash", models.CharField(max_length=255)),
                ("transaction_index", models.IntegerField()),
                ("contract_address", models.CharField(max_length=255)),
                ("block_number", models.IntegerField()),
                ("block_hash", models.CharField(max_length=255)),
                ("from_address", models.CharField(max_length=255)),
                ("to_address", models.CharField(max_length=255, null=True)),
                ("gas", models.CharField(max_length=255)),
                ("gas_price", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lp_pool_transaction",
            },
        ),
        migrations.CreateModel(
            name="TransactionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("topics", models.TextField()),
                ("data", models.TextField()),
                ("log_index", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="src.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "lp_pool_transaction_event",
            },
        ),
    ]
