# Generated by Django 4.1.7 on 2023-08-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_hash"], name="lp_pool_tra_transac_3ead09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionevent",
            index=models.Index(
                fields=["name", "transaction_id"], name="lp_pool_tra_name_aef13e_idx"
            ),
        ),
    ]
