# Generated by Django 4.1.7 on 2023-08-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0002_transaction_lp_pool_tra_transac_3ead09_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["contract_address"], name="lp_pool_tra_contrac_c01728_idx"
            ),
        ),
    ]
