# Generated by Django 4.1.7 on 2023-08-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0003_transaction_lp_pool_tra_contrac_c01728_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transactionevent",
            name="lp_pool_tra_name_aef13e_idx",
        ),
        migrations.AddIndex(
            model_name="transactionevent",
            index=models.Index(
                fields=["log_index", "transaction_id"],
                name="lp_pool_tra_log_ind_fdd242_idx",
            ),
        ),
    ]
