"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-yn^dlc9j100z&q5x!sx5m4*9z6g-k*zcibu_p3#f(fv=b&yr^z"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "src",
]

MIGRATION_MODULES = {
    "src": "migrations",
}
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "log_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/sinker.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console", "log_file"],
            "level": "INFO",
            "propagate": True,
        },
    },
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(name)s.%(funcName)s:%(lineno)s %(message)s"
        },
    },
}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "evm_lp_db.sqlite3",
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "<TAG>",
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "<TAG>"
EMAIL_HOST_PASSWORD = "<TAG>"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

LOGGING_EMAIL_RECIPIENT_LIST = ["hajdukbet@gmail.com"]

CHAIN_DEX_LP_CONFIG = {
    "PULSE": {
        "validator_node_url": "http://localhost:8545",
        "dexes": {
            "PULSEX": {
                "max_events_block_diff": 4320,
                "pools": {
                    "WPLS_DAI": {
                        "is_active": True,
                        "contract_address": "0xe56043671df55de5cdf8459710433c10324de0ae",
                    },
                    "USDC_WPLS": {
                        "is_active": True,
                        "contract_address": "0x6753560538ECa67617A9Ce605178F788bE7E524E",
                    },
                    "WPLS_USDT": {
                        "is_active": True,
                        "contract_address": "0xFadc475639131C1EAC3655c37EDA430851d53716",
                    },
                    "WBTC_WPLS": {
                        "is_active": True,
                        "contract_address": "0x46E27Ea3A035FfC9e6d6D56702CE3D208FF1e58c"
                    },
                    "WETH_WPLS": {
                        "is_active": True,
                        "contract_address": "0x42AbdFDB63f3282033C766E72Cc4810738571609"
                    },
                    "WPLS_stETH": {
                        "is_active": True,
                        "contract_address": "0xEFe14ed5fc8Fa9C3bD87cd3E0017235BcccF763e"
                    },
                    "PLSX_WPLS": {
                        "is_active": True,
                        "contract_address": "0x1b45b9148791d3a104184Cd5DFE5CE57193a3ee9"
                    },
                    "HEX_WPLS": {
                        "is_active": True,
                        "contract_address": "0xf1F4ee610b2bAbB05C635F726eF8B0C568c8dc65"
                    }
                },
            }
        },
    }
}
